import { Router } from 'express';
import authRouter from './auth.routes.js';
import vehicleTypeRouter from './vehicle-type.routes.js';
import brandRouter from './brand.routes.js';
import modelRouter from './model.routes.js';
import fuelTypeRouter from './fuel-type.routes.js';
import vehicleRouter from './vehicle.routes.js';
import customerRouter from './customer.routes.js';
import employeeRouter from './employee.routes.js';
import seasonalRateRouter from './seasonal-rate.routes.js';
import uploadRouter from './upload.routes.js';
import catalogRouter from './catalog.routes.js';
import reservationRouter from './reservation.routes.js';
import inspectionRouter from './inspection.routes.js';
import rentalRouter from './rental.routes.js';
import feeConfigRouter from './fee-config.routes.js';
import dashboardRouter from './dashboard.routes.js';
import reportRouter from './report.routes.js';
import gpsRouter from './gps.routes.js';
import queryRouter from './query.routes.js';
import policyRouter from './rental-policy.routes.js';
import companyInfoRouter from './company-info.routes.js';
import transactionRouter from './transaction.routes.js';
import damageTypeRouter from './damage-type.routes.js';

const router = Router();

router.use('/auth', authRouter);
router.use('/vehicle-types', vehicleTypeRouter);
router.use('/brands', brandRouter);
router.use('/models', modelRouter);
router.use('/fuel-types', fuelTypeRouter);
router.use('/vehicles', vehicleRouter);
router.use('/customers', customerRouter);
router.use('/employees', employeeRouter);
router.use('/seasonal-rates', seasonalRateRouter);
router.use('/uploads', uploadRouter);
router.use('/catalog', catalogRouter);
router.use('/reservations', reservationRouter);
router.use('/inspections', inspectionRouter);
router.use('/rentals', queryRouter);
router.use('/rentals', rentalRouter);
router.use('/fee-config', feeConfigRouter);
router.use('/dashboard', dashboardRouter);
router.use('/reports', reportRouter);
router.use('/gps', gpsRouter);
router.use('/policies', policyRouter);
router.use('/company', companyInfoRouter);
router.use('/transactions', transactionRouter);
router.use('/damage-types', damageTypeRouter);

export default router;
